Incremental compilation, step 3: separate .cc files (TUs) for each RAM-statement function.

diff --git a/src/souffle-compile.in b/src/souffle-compile.in
--- a/src/souffle-compile.in
+++ b/src/souffle-compile.in
@@ -15,7 +15,7 @@ usage() {
   printf "Name:
   souffle-compile - compile a C++ source file generated by souffle
 Usage:
-  souffle-compile [options] <FILE>.cpp
+  souffle-compile [options] <FILE>.cpp  <FILE>.cpp ...
 Options:
   -h           show usage
   -s           compile a program without OpenMP support
@@ -85,34 +85,38 @@ shift $(($OPTIND - 1))
 test -n "$1"
 error "no input file" $? 1
 
+MAINFILE=$1
+shift
+OTHERS="$@"
+
 # Check if the input file exists
-test -f "$1"
-error "cannot open source file: '$1'" $?
+test -f "$MAINFILE"
+error "cannot open source file: '$MAINFILE'" $?
 
 # Check if the input file has a valid extension
-exe=`basename $1 .cpp`
-test "$1" != "$exe"
-error "source file is not a .cpp file: '$1'" $?
+exe=`basename $MAINFILE .cpp`
+test "$MAINFILE" != "$exe"
+error "source file is not a .cpp file: '$MAINFILE'" $?
 
 # Ensure binary is compiled to same directory as cpp file
-cd "$(dirname $1)"
+cd "$(dirname $MAINFILE)"
 dir="$PWD"
 cd "$OLDPWD"
 
 # Compile
 rm -f $dir/$exe
-$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $1 $LIBS -I$HEADER_DIR $OMP_FLAG $LDFLAGS 2> $dir/$exe.$$.ccerr
+$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $MAINFILE $OTHERS $LIBS -I$HEADER_DIR $OMP_FLAG $LDFLAGS 2> $dir/$exe.$$.ccerr
 if test -f $dir/$exe
 then
   if [ "$WARNINGS" = 1 ]
   then
-     echo "$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $1 $LIBS -I$HEADER_DIR $OMP_FLAG"
+     echo "$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $MAINFILE $OTHERS $LIBS -I$HEADER_DIR $OMP_FLAG"
      cat $dir/$exe.$$.ccerr 1>&2
   fi
   rm $dir/$exe.$$.ccerr
 else
-  echo "compiler error: cannot compile source file $1" 1>&2
-  echo "$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $1 $LIBS -I$HEADER_DIR $OMP_FLAG"
+  echo "compiler error: cannot compile source file $MAINFILE" 1>&2
+  echo "$CXX $CXXFLAGS $CPPFLAGS -o$dir/$exe $MAINFILE $OTHERS $LIBS -I$HEADER_DIR $OMP_FLAG"
   cat $dir/$exe.$$.ccerr 1>&2
   rm -f $dir/$exe.$$.ccerr
   exit 1
